name: Ubuntu
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  release:
      types: [published]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        qt:
          - version: 6.5.3
            modules: qtwebengine qtwebchannel qtpositioning
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt.version }}
          modules: ${{ matrix.qt.modules }}
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build Ubuntu
        env:
          QT_VERSION: ${{ matrix.qt.version }}
          CMAKE_PREFIX_PATH: ${{ github.workspace }}/../Qt/${{ matrix.qt.version }}/gcc_64/lib/cmake
          CMAKE_BUILD_TYPE: Release
        run: |
          # ls -al ${{ github.workspace }}/..
          # ls -al ${{ github.workspace }}/../Qt/${{ matrix.qt.version }}
          # ls -al ${{ github.workspace }}/../Qt/${{ matrix.qt.version }}/gcc_64
          # ls -al ${{ github.workspace }}/../Qt/${{ matrix.qt.version }}/gcc_64/lib
          # ls -al ${{ github.workspace }}/../Qt/${{ matrix.qt.version }}/gcc_64/lib/cmake
          # ls -al
          mkdir build
          cd build
          cmake ..
          make
          cd ..
          ls -al build

      - name: Package Application
        run: |
          cd build
          os=$(echo "${{ matrix.os }}" | sed 's/-latest//')
          repository_name=$(basename ${{ github.repository }})
          zipfile=${repository_name}-${os}-${{ matrix.arch }}-${{ github.run_number }}.zip
          zip -r ${zipfile} ${repository_name}
          mv ${zipfile} ..
          cd ..
          ls -al
          echo "${zipfile}" > assets.txt

      - name: Create a Release
        if: ${{ github.event_name == 'release' }}
        id: create_release
        uses: shogo82148/actions-create-release@v1

      - name: Upload Assets
        if: ${{ github.event_name == 'release' }}
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GH_RELEASE_ACTION_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: assets.txt
